### ISSUE TITLE
[BUG] Main webpage throws warnings

### ISSUE THREAD

**Issue by RsTaK** [devstrons/heloworld#68]
### Description of the bug

![image](https://user-images.githubusercontent.com/37415061/134403523-244fd84c-0b3b-4e26-9a2a-78d569f31459.png)

### Steps to reproduce

Right click on the main page and to to the console log via :

-  Inspect ElementRight-click

### Expected behavior

_

### Desktop (please complete the information in the place holder)

_

### Smartphone (please complete the information in the place holder)

_

**Comment by amino19** [comment]
@RsTaK: We're going to close this issue, as we're migrating the whole front-end to NextJS, you can check out: #96 

Also, the back-end has been fixed by @tgoyal63. For any further queries, let's meet at Discord's voice channel.

Even after as discussed by you & other folks, we're soon going to start our project discussions on weekends. Let's catch up!

**Comment by aminoxix** [comment]
@RsTaK: It's fixed now! :hammer_and_wrench: 

Thank you so much for raising this issue, in aspects with a bug you saw :eyes:

We really love the way you present & decided to giveaway a Replit Hacker Plan, let's catch up on DM! :mailbox_with_mail: |

![image](https://user-images.githubusercontent.com/75872316/166584089-87702e8c-3872-4c19-b6f2-9f5c4657355a.png)
